baseURL = "https://www.pukara.es/"
defaultContentLanguage = "es"
title = "Pukara"

[languages]
    [languages.es]
        languageName = "Es"
        baseURL = "https://www.pukara.es/es/"
        weight = 1
        title = "Pukara Es"
        contentDir = "content/espanol"


    [languages.en]
        languageName = "En"
        baseURL = "https://www.pukara.es/en/"
        weight = 2
        title = "Pukara En"
        contentDir = "content/english"

    [languages.pt-br]
        languageName = "Pt-Br"
        baseURL = "https://www.pukara.es/pt-br/"
        weight = 3
        title = "Pukara Pt-Br"
        contentDir = "content/portugues"

